runtime: python37

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

# env_variables:
#   GA_TRACKING_ID: UA-11213581-15

handlers:
  - url: /(.*\.(js|css))$
    static_files: build/\1
    upload: build/.*\.(js|css)$

  - url: /.*
    secure: always
    script: backend.app
