runtime: python37

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  FLAG_ENABLE_HEADER: False 
  FLAG_ENABLE_CALLS: True
#   GA_TRACKING_ID: UA-11213581-15
#
#

handlers:
  - url: /static
    static_dir: static
  - url: /build
    static_dir: build
  - url: /.*
    secure: always
    script: auto
